### ISSUE TITLE
Sapo marako

### ISSUE THREAD

**Issue by tomicapretto** [mimo-dev/js-xmas-edition#1]
Tu primer issue wn qlo

**Comment by mimo-dev** [comment]
Que hago con esto?

**Comment by tomicapretto** [comment]
Nada, los issues se usan para reportar problemas, mandar sugerencias, etc. 
La idea es que cuando el problema/duda se resuelve, el issue se cierra.

Lo puedo hacer yo (porque soy quien abrio el issue) o lo podes hacer vos (porque sos dueno del repo)

**Comment by mimo-dev** [comment]
Ahh, jaja. Gracias bola, bueno si no encontrar nada choto lo cierro
